name: shapeshift
description: A sample command-line application
dependencies:
  args: '>=0.12.0'
  browser: any
  diff_match_patch: '>=0.2.1'
  html5lib: any
  json_diff: '>=0.1.0 <1.0.0'
  route: any
dev_dependencies:
  unittest: '>=0.11.0'
